# LESSON 4: NUMPY INTRODUCTION
<img src="image/np_logo.png" width="400px"/>

## 1. Overall introduction

## 2. Install and import numpy

In [1]:
!pip install numpy

You should consider upgrading via the '/Users/nguyenhuuminh/Works/env/bin/python -m pip install --upgrade pip' command.


In [2]:
import numpy as np

## 3. Get started with numpy ndarray
<img src="image/np_array.png" width="500px"/>

### Create ndarray
| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats|

In [3]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [6]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.41114499, 0.08571136, 0.23351232],
       [0.1512306 , 0.93938668, 0.05790795],
       [0.71087702, 0.60062989, 0.65785836]])

In [9]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.43431537,  0.93645415, -0.58962538],
       [ 0.19231635,  0.44980668, -0.04747245],
       [ 0.00904111,  1.42545632, -0.85636919]])

### Show ndarray's attributes

In [10]:
x = np.random.randint(10, size=(3, 4, 5))
x

array([[[8, 1, 2, 2, 2],
        [4, 5, 3, 7, 6],
        [5, 0, 8, 0, 3],
        [0, 4, 2, 0, 8]],

       [[9, 2, 1, 4, 6],
        [6, 9, 5, 6, 6],
        [1, 7, 0, 3, 3],
        [0, 9, 7, 2, 1]],

       [[2, 3, 4, 6, 0],
        [5, 6, 9, 0, 1],
        [4, 2, 5, 4, 6],
        [9, 9, 1, 7, 3]]])

In [11]:
x.ndim # Number of dimensions

3

In [12]:
x.shape # Detail size each dimension

(3, 4, 5)

In [13]:
x.size # Total elements in array

60

In [14]:
x.dtype # Data type used in array

dtype('int64')

In [15]:
x.itemsize # Size (in bytes) of each element

8

In [16]:
x.nbytes # Total size of all elements in array

480

### Access elements in ndarray by index

In [17]:
x

array([[[8, 1, 2, 2, 2],
        [4, 5, 3, 7, 6],
        [5, 0, 8, 0, 3],
        [0, 4, 2, 0, 8]],

       [[9, 2, 1, 4, 6],
        [6, 9, 5, 6, 6],
        [1, 7, 0, 3, 3],
        [0, 9, 7, 2, 1]],

       [[2, 3, 4, 6, 0],
        [5, 6, 9, 0, 1],
        [4, 2, 5, 4, 6],
        [9, 9, 1, 7, 3]]])

In [18]:
x[1]

array([[9, 2, 1, 4, 6],
       [6, 9, 5, 6, 6],
       [1, 7, 0, 3, 3],
       [0, 9, 7, 2, 1]])

In [19]:
x[1, 1]

array([6, 9, 5, 6, 6])

In [20]:
x[1, 1, 1]

9

In [21]:
x[1, 1, 1] = 999
x

array([[[  8,   1,   2,   2,   2],
        [  4,   5,   3,   7,   6],
        [  5,   0,   8,   0,   3],
        [  0,   4,   2,   0,   8]],

       [[  9,   2,   1,   4,   6],
        [  6, 999,   5,   6,   6],
        [  1,   7,   0,   3,   3],
        [  0,   9,   7,   2,   1]],

       [[  2,   3,   4,   6,   0],
        [  5,   6,   9,   0,   1],
        [  4,   2,   5,   4,   6],
        [  9,   9,   1,   7,   3]]])

In [22]:
x[-1]

array([[2, 3, 4, 6, 0],
       [5, 6, 9, 0, 1],
       [4, 2, 5, 4, 6],
       [9, 9, 1, 7, 3]])

### Slice ndarray by index and `:`
<img src="image/np_slice.jpeg" width="400px"/>

In [23]:
x

array([[[  8,   1,   2,   2,   2],
        [  4,   5,   3,   7,   6],
        [  5,   0,   8,   0,   3],
        [  0,   4,   2,   0,   8]],

       [[  9,   2,   1,   4,   6],
        [  6, 999,   5,   6,   6],
        [  1,   7,   0,   3,   3],
        [  0,   9,   7,   2,   1]],

       [[  2,   3,   4,   6,   0],
        [  5,   6,   9,   0,   1],
        [  4,   2,   5,   4,   6],
        [  9,   9,   1,   7,   3]]])

In [24]:
x[1:]

array([[[  9,   2,   1,   4,   6],
        [  6, 999,   5,   6,   6],
        [  1,   7,   0,   3,   3],
        [  0,   9,   7,   2,   1]],

       [[  2,   3,   4,   6,   0],
        [  5,   6,   9,   0,   1],
        [  4,   2,   5,   4,   6],
        [  9,   9,   1,   7,   3]]])

In [25]:
x[1:, 1:]

array([[[  6, 999,   5,   6,   6],
        [  1,   7,   0,   3,   3],
        [  0,   9,   7,   2,   1]],

       [[  5,   6,   9,   0,   1],
        [  4,   2,   5,   4,   6],
        [  9,   9,   1,   7,   3]]])

In [26]:
x[1:, 1:, 1:]

array([[[999,   5,   6,   6],
        [  7,   0,   3,   3],
        [  9,   7,   2,   1]],

       [[  6,   9,   0,   1],
        [  2,   5,   4,   6],
        [  9,   1,   7,   3]]])

In [27]:
x[1:, 1:, 1:] = np.full((2, 3, 4), 888)
x

array([[[  8,   1,   2,   2,   2],
        [  4,   5,   3,   7,   6],
        [  5,   0,   8,   0,   3],
        [  0,   4,   2,   0,   8]],

       [[  9,   2,   1,   4,   6],
        [  6, 888, 888, 888, 888],
        [  1, 888, 888, 888, 888],
        [  0, 888, 888, 888, 888]],

       [[  2,   3,   4,   6,   0],
        [  5, 888, 888, 888, 888],
        [  4, 888, 888, 888, 888],
        [  9, 888, 888, 888, 888]]])

### Slice ndarray with step

In [28]:
y = x[0, 0]
y

array([8, 1, 2, 2, 2])

In [29]:
y[::2] # start = 0 (first index), stop = 5 (last index + 1), step = 2

array([8, 2, 2])

In [30]:
y[::-2] # step is negative => start and stop are swapped

array([2, 2, 8])

## 4. Simple functions with ndarray
### Reshape ndarray

In [121]:
z = np.arange(12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
z.shape

(12,)

In [123]:
z.reshape((12, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [124]:
z.reshape((1, 12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [125]:
z.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [126]:
z.reshape((2, 2, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Change number of dims, position of dims
#### Change number of dims by using `np.expand_dims()` and `np.squeeze()`

In [127]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
z.shape

(12,)

In [134]:
z_1 = np.expand_dims(z, axis=1)
z_1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [135]:
z_1.shape

(12, 1)

In [137]:
z_0 = np.expand_dims(z, axis=0)
z_0

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [138]:
z_0.shape

(1, 12)

In [141]:
np.squeeze(z_0, axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
np.squeeze(z_1, axis=1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Change position of dims by using `np.transpose()`

In [150]:
z_1_trans = np.transpose(z_1, [1, 0])
z_1_trans

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [151]:
z_1_trans.shape

(1, 12)

### Concatenate ndarray
#### Using `np.concatenate()`

In [37]:
x = np.array([1, 2, 3])
y = np.array([4.4, 5.5, 6.6])
z = np.array([7.77, 8.88, 9.99])

In [38]:
np.concatenate([x, y])

array([1. , 2. , 3. , 4.4, 5.5, 6.6])

In [39]:
np.concatenate([x, y, z])

array([1.  , 2.  , 3.  , 4.4 , 5.5 , 6.6 , 7.77, 8.88, 9.99])

In [40]:
xx = np.array([[1, 2, 3], [3, 2, 1]])
yy = np.array([[4.4, 5.5, 6.6], [6.6, 5.5, 4.4]])

In [41]:
np.concatenate([xx, yy], axis=0)

array([[1. , 2. , 3. ],
       [3. , 2. , 1. ],
       [4.4, 5.5, 6.6],
       [6.6, 5.5, 4.4]])

In [42]:
np.concatenate([xx, yy], axis=1)

array([[1. , 2. , 3. , 4.4, 5.5, 6.6],
       [3. , 2. , 1. , 6.6, 5.5, 4.4]])

#### Using `np.hstack()`(horizontal stack),  `np.vstack()`(vertical stack) and `np.dstack()`(depth stack)

In [43]:
np.hstack([xx, yy])

array([[1. , 2. , 3. , 4.4, 5.5, 6.6],
       [3. , 2. , 1. , 6.6, 5.5, 4.4]])

In [44]:
np.vstack([xx, yy])

array([[1. , 2. , 3. ],
       [3. , 2. , 1. ],
       [4.4, 5.5, 6.6],
       [6.6, 5.5, 4.4]])

In [45]:
np.dstack([xx, yy])

array([[[1. , 4.4],
        [2. , 5.5],
        [3. , 6.6]],

       [[3. , 6.6],
        [2. , 5.5],
        [1. , 4.4]]])

## 5. Computation on ndarrays
| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

In [46]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [47]:
y = np.arange(10, 20, 2)
y

array([10, 12, 14, 16, 18])

In [48]:
x + 10

array([10, 11, 12, 13, 14])

In [49]:
np.add(x, 10)

array([10, 11, 12, 13, 14])

In [50]:
x + y

array([10, 13, 16, 19, 22])

In [51]:
np.add(x, y)

array([10, 13, 16, 19, 22])

In [52]:
x - 2

array([-2, -1,  0,  1,  2])

In [53]:
np.subtract(x, 2)

array([-2, -1,  0,  1,  2])

In [54]:
x - y

array([-10, -11, -12, -13, -14])

In [55]:
np.subtract(x, y)

array([-10, -11, -12, -13, -14])

In [56]:
x * 3

array([ 0,  3,  6,  9, 12])

In [57]:
np.multiply(x, 3)

array([ 0,  3,  6,  9, 12])

In [58]:
x * y

array([ 0, 12, 28, 48, 72])

In [59]:
np.multiply(x, y)

array([ 0, 12, 28, 48, 72])

In [60]:
x / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [61]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5, 2. ])

In [62]:
x / y

array([0.        , 0.08333333, 0.14285714, 0.1875    , 0.22222222])

In [63]:
np.divide(x, y)

array([0.        , 0.08333333, 0.14285714, 0.1875    , 0.22222222])

In [64]:
x // 2

array([0, 0, 1, 1, 2])

In [65]:
np.floor_divide(x, 2)

array([0, 0, 1, 1, 2])

In [66]:
x // y

array([0, 0, 0, 0, 0])

In [67]:
np.floor_divide(x, y)

array([0, 0, 0, 0, 0])

In [68]:
x % 2

array([0, 1, 0, 1, 0])

In [69]:
np.mod(x, 2)

array([0, 1, 0, 1, 0])

In [70]:
x % y

array([0, 1, 2, 3, 4])

In [71]:
np.mod(x, y)

array([0, 1, 2, 3, 4])

In [72]:
x ** 2

array([ 0,  1,  4,  9, 16])

In [73]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16])

In [74]:
x ** y

array([          0,           1,       16384,    43046721, 68719476736])

In [75]:
np.power(x, y)

array([          0,           1,       16384,    43046721, 68719476736])

In [76]:
pi_array = np.linspace(-1 * np.pi, np.pi, 5)
pi_array

array([-3.14159265, -1.57079633,  0.        ,  1.57079633,  3.14159265])

In [77]:
np.sin(pi_array)

array([-1.2246468e-16, -1.0000000e+00,  0.0000000e+00,  1.0000000e+00,
        1.2246468e-16])

In [78]:
np.cos(pi_array)

array([-1.000000e+00,  6.123234e-17,  1.000000e+00,  6.123234e-17,
       -1.000000e+00])

In [79]:
np.tan(pi_array)

array([ 1.22464680e-16, -1.63312394e+16,  0.00000000e+00,  1.63312394e+16,
       -1.22464680e-16])

In [80]:
np.arcsin(np.sin(pi_array))

array([-1.22464680e-16, -1.57079633e+00,  0.00000000e+00,  1.57079633e+00,
        1.22464680e-16])

In [81]:
np.arccos(np.cos(pi_array))

array([3.14159265, 1.57079633, 0.        , 1.57079633, 3.14159265])

In [82]:
np.arctan(np.tan(pi_array))

array([ 1.22464680e-16, -1.57079633e+00,  0.00000000e+00,  1.57079633e+00,
       -1.22464680e-16])

In [83]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [84]:
np.exp2(x)

array([ 1.,  2.,  4.,  8., 16.])

In [85]:
np.power(3, x)

array([ 1,  3,  9, 27, 81])

In [86]:
np.log(x)

/var/folders/9m/8kxkp3s10g9gnjlz2bk_8zs00000gp/T/ipykernel_47780/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [87]:
np.log2(x)

/var/folders/9m/8kxkp3s10g9gnjlz2bk_8zs00000gp/T/ipykernel_47780/3275510840.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([     -inf, 0.       , 1.       , 1.5849625, 2.       ])

In [88]:
np.log10(x)

/var/folders/9m/8kxkp3s10g9gnjlz2bk_8zs00000gp/T/ipykernel_47780/1114196279.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(x)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999])

## 6. Data aggregation on ndarray
|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |


### Compare between built-in python `sum()` and `np.sum()`

In [89]:
big_array = np.random.rand(1000000)

In [90]:
sum(big_array)

499985.9925345513

In [91]:
np.sum(big_array)

499985.99253454496

In [92]:
%timeit sum(big_array)

102 ms ± 6.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [93]:
%timeit np.sum(big_array)

653 µs ± 173 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [94]:
x = np.random.randint(0, 10, (2, 5))
x

array([[6, 8, 1, 4, 8],
       [5, 6, 0, 1, 3]])

In [95]:
sum(x)

array([11, 14,  1,  5, 11])

In [96]:
np.sum(x)

42

In [97]:
np.sum(x, axis=1)

array([27, 15])

In [98]:
np.sum(x, axis=0)

array([11, 14,  1,  5, 11])

### Compare between built-in python `min() max()` and `np.min(), np.max()`

In [99]:
min(big_array), max(big_array)

(2.2762304707768521e-07, 0.9999971793568796)

In [100]:
np.min(big_array), np.max(big_array)

(2.2762304707768521e-07, 0.9999971793568796)

In [101]:
%timeit min(big_array)
%timeit np.min(big_array)

99.6 ms ± 22.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
815 µs ± 348 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [102]:
%timeit max(big_array)
%timeit np.max(big_array)

118 ms ± 43.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
671 µs ± 103 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [103]:
x

array([[6, 8, 1, 4, 8],
       [5, 6, 0, 1, 3]])

In [104]:
min(x), max(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [105]:
np.min(x), np.max(x)

(0, 8)

In [106]:
np.min(x, axis=0), np.max(x, axis=0)

(array([5, 6, 0, 1, 3]), array([6, 8, 1, 4, 8]))

In [107]:
np.min(x, axis=1), np.max(x, axis=1)

(array([1, 0]), array([8, 6]))

## 7. Ndarray with logical functions
### Simple logical functions

In [108]:
x

array([[6, 8, 1, 4, 8],
       [5, 6, 0, 1, 3]])

In [109]:
x > 2

array([[ True,  True, False,  True,  True],
       [ True,  True, False, False,  True]])

In [110]:
x >= 2

array([[ True,  True, False,  True,  True],
       [ True,  True, False, False,  True]])

In [111]:
x < 2

array([[False, False,  True, False, False],
       [False, False,  True,  True, False]])

In [112]:
x <= 2

array([[False, False,  True, False, False],
       [False, False,  True,  True, False]])

In [113]:
x == 2

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [114]:
x != 2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [115]:
np.all(x > 2)

False

In [116]:
np.all(x >= 1)

False

In [117]:
np.any(x > 2)

True

In [119]:
np.any(x < 0)

False

### Use ogical functions as mask

In [152]:
x

array([[6, 8, 1, 4, 8],
       [5, 6, 0, 1, 3]])

In [153]:
x > 3

array([[ True,  True, False,  True,  True],
       [ True,  True, False, False, False]])

In [154]:
x[x > 3]

array([6, 8, 4, 8, 5, 6])

## 8. Homework
2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.
3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
6. Write a NumPy program to reverse an array (first element becomes last).
7. Write a NumPy program to convert an array to a float type
8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.
5. Write a NumPy program to get the indices of the sorted elements of a given array.