# LESSON 3: NUMPY INTRODUCTION
<img src="../images/np_logo.png" width="400px"/>

## 1. Overall introduction
"The fundamental package for scientific computing with Python." <br>
NumPy official document is available [here](https://numpy.org/doc/stable/). <br>
NumPy official open-source is [here](https://github.com/numpy/numpy). <br>
Compare with Python `list`, NumPy is FAST and MEMORY EFFIENCY!!! (computing on vector and single data type)

### 1.1. Vectorization
#### Using Python list

In [1]:
list_a = [1, 2, 3] * 1_000_000
list_b = [10, 11, 12] * 1_000_000
list_results = []

In [2]:
%%timeit

for index in range(len(list_a)):
    list_results.append(list_a[index] + list_b[index])

# print(list_results)

1.66 s ± 373 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### Using Numpy

In [3]:
import numpy as np

np_a = np.array([1, 2, 3] * 1_000_000)
np_b = np.array([10, 11, 12] * 1_000_000)

In [4]:
%%timeit

np_results = np_a + np_b
# print(np_results)

36.4 ms ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 1.2. Broadcasting
<img src="../images/np_broadcast_1.png" width="400px"/>

In the simplest example of broadcasting, the scalar `b` is stretched to become an array of same shape as `a` so the shapes are compatible for element-by-element multiplication.

<img src="../images/np_broadcast_2.png" width="400px"/>

A two dimensional array added by a one dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

<img src="../images/np_broadcast_3.png" width="400px"/>

In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.

<img src="../images/np_broadcast_4.png" width="400px"/>

When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.

## 2. Install and import numpy
Install numpy by running this command in jupyter notebook: 
`!conda install -c anaconda numpy -y`

In [5]:
import numpy as np

## 3. Get started with numpy ndarray
<img src="../images/np_array.png" width="500px"/>

### Create ndarray
| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats|

In [6]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [9]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.93503613, 0.47501936, 0.25422422],
       [0.17186271, 0.8528327 , 0.77554851],
       [0.78370314, 0.80154891, 0.05450375]])

In [12]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.86653221,  0.60520546,  0.61013662],
       [-0.34259552,  1.01494773, -1.04901432],
       [-0.5974368 ,  1.4509601 , -1.1005172 ]])

### Show ndarray's attributes

In [13]:
x = np.random.randint(10, size=(3, 4, 5))
x

array([[[8, 1, 7, 8, 6],
        [9, 1, 2, 9, 7],
        [1, 1, 0, 3, 5],
        [5, 9, 2, 2, 8]],

       [[5, 3, 7, 9, 3],
        [8, 9, 8, 5, 8],
        [8, 0, 8, 7, 1],
        [1, 6, 9, 0, 2]],

       [[5, 1, 8, 6, 1],
        [0, 6, 7, 4, 2],
        [6, 7, 7, 5, 2],
        [7, 7, 7, 8, 6]]])

In [14]:
x.ndim # Number of dimensions

3

In [15]:
x.shape # Detail size each dimension

(3, 4, 5)

In [16]:
x.size # Total elements in array

60

In [17]:
x.dtype # Data type used in array

dtype('int64')

In [18]:
x.itemsize # Size (in bytes) of each element

8

In [19]:
x.nbytes # Total size of all elements in array

480

### Access elements in ndarray by index

In [20]:
x

array([[[8, 1, 7, 8, 6],
        [9, 1, 2, 9, 7],
        [1, 1, 0, 3, 5],
        [5, 9, 2, 2, 8]],

       [[5, 3, 7, 9, 3],
        [8, 9, 8, 5, 8],
        [8, 0, 8, 7, 1],
        [1, 6, 9, 0, 2]],

       [[5, 1, 8, 6, 1],
        [0, 6, 7, 4, 2],
        [6, 7, 7, 5, 2],
        [7, 7, 7, 8, 6]]])

In [21]:
x[1]

array([[5, 3, 7, 9, 3],
       [8, 9, 8, 5, 8],
       [8, 0, 8, 7, 1],
       [1, 6, 9, 0, 2]])

In [22]:
x[1, 1]

array([8, 9, 8, 5, 8])

In [23]:
x[1, 1, 1]

9

In [24]:
x[1, 1, 1] = 999
x

array([[[  8,   1,   7,   8,   6],
        [  9,   1,   2,   9,   7],
        [  1,   1,   0,   3,   5],
        [  5,   9,   2,   2,   8]],

       [[  5,   3,   7,   9,   3],
        [  8, 999,   8,   5,   8],
        [  8,   0,   8,   7,   1],
        [  1,   6,   9,   0,   2]],

       [[  5,   1,   8,   6,   1],
        [  0,   6,   7,   4,   2],
        [  6,   7,   7,   5,   2],
        [  7,   7,   7,   8,   6]]])

In [25]:
x[-1]

array([[5, 1, 8, 6, 1],
       [0, 6, 7, 4, 2],
       [6, 7, 7, 5, 2],
       [7, 7, 7, 8, 6]])

### Slice ndarray by index and `:`
<img src="../images/np_slice.jpeg" width="400px"/>

In [26]:
x

array([[[  8,   1,   7,   8,   6],
        [  9,   1,   2,   9,   7],
        [  1,   1,   0,   3,   5],
        [  5,   9,   2,   2,   8]],

       [[  5,   3,   7,   9,   3],
        [  8, 999,   8,   5,   8],
        [  8,   0,   8,   7,   1],
        [  1,   6,   9,   0,   2]],

       [[  5,   1,   8,   6,   1],
        [  0,   6,   7,   4,   2],
        [  6,   7,   7,   5,   2],
        [  7,   7,   7,   8,   6]]])

In [27]:
x[1:]

array([[[  5,   3,   7,   9,   3],
        [  8, 999,   8,   5,   8],
        [  8,   0,   8,   7,   1],
        [  1,   6,   9,   0,   2]],

       [[  5,   1,   8,   6,   1],
        [  0,   6,   7,   4,   2],
        [  6,   7,   7,   5,   2],
        [  7,   7,   7,   8,   6]]])

In [28]:
x[1:, 1:]

array([[[  8, 999,   8,   5,   8],
        [  8,   0,   8,   7,   1],
        [  1,   6,   9,   0,   2]],

       [[  0,   6,   7,   4,   2],
        [  6,   7,   7,   5,   2],
        [  7,   7,   7,   8,   6]]])

In [29]:
x[1:, 1:, 1:]

array([[[999,   8,   5,   8],
        [  0,   8,   7,   1],
        [  6,   9,   0,   2]],

       [[  6,   7,   4,   2],
        [  7,   7,   5,   2],
        [  7,   7,   8,   6]]])

In [30]:
x[1:, 1:, 1:] = np.full((2, 3, 4), 888)
x

array([[[  8,   1,   7,   8,   6],
        [  9,   1,   2,   9,   7],
        [  1,   1,   0,   3,   5],
        [  5,   9,   2,   2,   8]],

       [[  5,   3,   7,   9,   3],
        [  8, 888, 888, 888, 888],
        [  8, 888, 888, 888, 888],
        [  1, 888, 888, 888, 888]],

       [[  5,   1,   8,   6,   1],
        [  0, 888, 888, 888, 888],
        [  6, 888, 888, 888, 888],
        [  7, 888, 888, 888, 888]]])

### Slice ndarray with step

In [31]:
y = x[0, 0]
y

array([8, 1, 7, 8, 6])

In [32]:
y[::2] # start = 0 (first index), stop = 5 (last index + 1), step = 2

array([8, 7, 6])

In [33]:
y[::-2] # step is negative => start and stop are swapped

array([6, 7, 8])

## 4. Computation on ndarrays
| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

In [34]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [35]:
y = np.arange(10, 20, 2)
y

array([10, 12, 14, 16, 18])

In [36]:
x + 10

array([10, 11, 12, 13, 14])

In [37]:
np.add(x, 10)

array([10, 11, 12, 13, 14])

In [38]:
x + y

array([10, 13, 16, 19, 22])

In [39]:
np.add(x, y)

array([10, 13, 16, 19, 22])

In [40]:
x - 2

array([-2, -1,  0,  1,  2])

In [41]:
np.subtract(x, 2)

array([-2, -1,  0,  1,  2])

In [42]:
x - y

array([-10, -11, -12, -13, -14])

In [43]:
np.subtract(x, y)

array([-10, -11, -12, -13, -14])

In [44]:
x * 3

array([ 0,  3,  6,  9, 12])

In [45]:
np.multiply(x, 3)

array([ 0,  3,  6,  9, 12])

In [46]:
x * y

array([ 0, 12, 28, 48, 72])

In [47]:
np.multiply(x, y)

array([ 0, 12, 28, 48, 72])

In [48]:
x / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [49]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5, 2. ])

In [50]:
x / y

array([0.        , 0.08333333, 0.14285714, 0.1875    , 0.22222222])

In [51]:
np.divide(x, y)

array([0.        , 0.08333333, 0.14285714, 0.1875    , 0.22222222])

In [52]:
x // 2

array([0, 0, 1, 1, 2])

In [53]:
np.floor_divide(x, 2)

array([0, 0, 1, 1, 2])

In [54]:
x // y

array([0, 0, 0, 0, 0])

In [55]:
np.floor_divide(x, y)

array([0, 0, 0, 0, 0])

In [56]:
x % 2

array([0, 1, 0, 1, 0])

In [57]:
np.mod(x, 2)

array([0, 1, 0, 1, 0])

In [58]:
x % y

array([0, 1, 2, 3, 4])

In [59]:
np.mod(x, y)

array([0, 1, 2, 3, 4])

In [60]:
x ** 2

array([ 0,  1,  4,  9, 16])

In [61]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16])

In [62]:
x ** y

array([          0,           1,       16384,    43046721, 68719476736])

In [63]:
np.power(x, y)

array([          0,           1,       16384,    43046721, 68719476736])

In [64]:
pi_array = np.linspace(-1 * np.pi, np.pi, 5)
pi_array

array([-3.14159265, -1.57079633,  0.        ,  1.57079633,  3.14159265])

In [65]:
np.sin(pi_array)

array([-1.2246468e-16, -1.0000000e+00,  0.0000000e+00,  1.0000000e+00,
        1.2246468e-16])

In [66]:
np.cos(pi_array)

array([-1.000000e+00,  6.123234e-17,  1.000000e+00,  6.123234e-17,
       -1.000000e+00])

In [67]:
np.tan(pi_array)

array([ 1.22464680e-16, -1.63312394e+16,  0.00000000e+00,  1.63312394e+16,
       -1.22464680e-16])

In [68]:
np.arcsin(np.sin(pi_array))

array([-1.22464680e-16, -1.57079633e+00,  0.00000000e+00,  1.57079633e+00,
        1.22464680e-16])

In [69]:
np.arccos(np.cos(pi_array))

array([3.14159265, 1.57079633, 0.        , 1.57079633, 3.14159265])

In [70]:
np.arctan(np.tan(pi_array))

array([ 1.22464680e-16, -1.57079633e+00,  0.00000000e+00,  1.57079633e+00,
       -1.22464680e-16])

In [71]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [72]:
np.exp2(x)

array([ 1.,  2.,  4.,  8., 16.])

In [73]:
np.power(3, x)

array([ 1,  3,  9, 27, 81])

In [74]:
np.log(x + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [75]:
np.log2(x + 1)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [76]:
np.log10(x + 1)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

## 5. Simple functions with ndarray
### Reshape ndarray

In [77]:
z = np.arange(12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
z.shape

(12,)

In [79]:
z_reshape = z.reshape((12, 1))
z_reshape

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [80]:
z_reshape.shape

(12, 1)

In [81]:
z_reshape = z.reshape((1, 12))
z_reshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [82]:
z_reshape.shape

(1, 12)

In [83]:
z.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [84]:
z.reshape((2, 2, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Using `-1` as a size while reshaping, `numpy` will automatically calculate this size.

In [85]:
z.reshape((4, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
z.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
z.reshape((-1, 2, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [88]:
z.reshape((2, 2, -1))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [89]:
z.reshape((-1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Change number of dims, position of dims
#### Change number of dims by using `np.expand_dims()` and `np.squeeze()`

In [90]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
z.shape

(12,)

In [92]:
z_1 = np.expand_dims(z, axis=1)
z_1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [93]:
z_1.shape

(12, 1)

In [94]:
z_0 = np.expand_dims(z, axis=0)
z_0

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [95]:
z_0.shape

(1, 12)

In [96]:
np.squeeze(z_0, axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
np.squeeze(z_1, axis=1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Change position of dims by using `np.transpose()`

In [98]:
z_1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [99]:
z_1.shape

(12, 1)

In [100]:
z_1_trans = np.transpose(z_1, [1, 0])
z_1_trans

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [101]:
z_1_trans.shape

(1, 12)

### Concatenate ndarray
#### Using `np.concatenate()`

In [102]:
x = np.array([1, 2, 3])
y = np.array([4.4, 5.5, 6.6])
z = np.array([7.77, 8.88, 9.99])

In [103]:
x

array([1, 2, 3])

In [104]:
y

array([4.4, 5.5, 6.6])

In [105]:
z

array([7.77, 8.88, 9.99])

In [106]:
np.concatenate([x, y])

array([1. , 2. , 3. , 4.4, 5.5, 6.6])

In [107]:
np.concatenate([x, y, z])

array([1.  , 2.  , 3.  , 4.4 , 5.5 , 6.6 , 7.77, 8.88, 9.99])

In [108]:
xx = np.array([[1, 2, 3], [3, 2, 1]])
yy = np.array([[4.4, 5.5, 6.6], [6.6, 5.5, 4.4]])

In [109]:
xx.shape

(2, 3)

In [110]:
yy.shape

(2, 3)

In [111]:
np.concatenate([xx, yy], axis=0)

array([[1. , 2. , 3. ],
       [3. , 2. , 1. ],
       [4.4, 5.5, 6.6],
       [6.6, 5.5, 4.4]])

In [112]:
np.concatenate([xx, yy], axis=1)

array([[1. , 2. , 3. , 4.4, 5.5, 6.6],
       [3. , 2. , 1. , 6.6, 5.5, 4.4]])

#### Using `np.hstack()`(horizontal stack),  `np.vstack()`(vertical stack) and `np.dstack()`(depth stack)

In [113]:
np.hstack([xx, yy])

array([[1. , 2. , 3. , 4.4, 5.5, 6.6],
       [3. , 2. , 1. , 6.6, 5.5, 4.4]])

In [114]:
np.vstack([xx, yy])

array([[1. , 2. , 3. ],
       [3. , 2. , 1. ],
       [4.4, 5.5, 6.6],
       [6.6, 5.5, 4.4]])

In [115]:
np.dstack([xx, yy])

array([[[1. , 4.4],
        [2. , 5.5],
        [3. , 6.6]],

       [[3. , 6.6],
        [2. , 5.5],
        [1. , 4.4]]])

## 6. Data aggregation on ndarray
|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |


### Compare between built-in python `sum()` and `np.sum()`

In [116]:
big_array = np.random.rand(1_000_000)
big_array.shape

(1000000,)

In [117]:
sum(big_array)

499657.5127690722

In [118]:
np.sum(big_array)

499657.5127690813

In [119]:
%timeit sum(big_array)

273 ms ± 64 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [120]:
%timeit np.sum(big_array)

1 ms ± 122 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [121]:
x = np.random.randint(0, 10, (2, 5))
x

array([[7, 0, 5, 7, 7],
       [0, 5, 0, 8, 3]])

In [122]:
sum(x)

array([ 7,  5,  5, 15, 10])

In [123]:
np.sum(x)

42

In [124]:
np.sum(x, axis=1)

array([26, 16])

In [125]:
np.sum(x, axis=0)

array([ 7,  5,  5, 15, 10])

### Compare between built-in python `min(), max()` and `np.min(), np.max()`

In [126]:
min(big_array), max(big_array)

(1.8827723027303733e-06, 0.999999242502268)

In [127]:
np.min(big_array), np.max(big_array)

(1.8827723027303733e-06, 0.999999242502268)

In [128]:
%timeit min(big_array)
%timeit np.min(big_array)

288 ms ± 98.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.46 ms ± 101 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [129]:
%timeit max(big_array)
%timeit np.max(big_array)

312 ms ± 95.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.29 ms ± 395 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [130]:
x

array([[7, 0, 5, 7, 7],
       [0, 5, 0, 8, 3]])

In [131]:
x.shape

(2, 5)

In [132]:
min(x), max(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [133]:
np.min(x), np.max(x)

(0, 8)

In [134]:
np.min(x, axis=0), np.max(x, axis=0)

(array([0, 0, 0, 7, 3]), array([7, 5, 5, 8, 7]))

In [135]:
np.min(x, axis=1), np.max(x, axis=1)

(array([0, 0]), array([7, 8]))

In [136]:
x

array([[7, 0, 5, 7, 7],
       [0, 5, 0, 8, 3]])

In [137]:
np.any(x > 3)

True

In [138]:
np.all(x > 3)

False

## 7. Ndarray with logical functions
### Simple logical functions

In [139]:
x

array([[7, 0, 5, 7, 7],
       [0, 5, 0, 8, 3]])

In [140]:
x > 2

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True]])

In [141]:
x >= 2

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True]])

In [142]:
x < 2

array([[False,  True, False, False, False],
       [ True, False,  True, False, False]])

In [143]:
x <= 2

array([[False,  True, False, False, False],
       [ True, False,  True, False, False]])

In [144]:
x == 2

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [145]:
x != 2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [146]:
np.all(x > 2)

False

In [147]:
np.all(x >= 0)

True

In [148]:
np.any(x > 2)

True

In [149]:
np.any(x < 0)

False

### Use logical functions as mask

In [150]:
x

array([[7, 0, 5, 7, 7],
       [0, 5, 0, 8, 3]])

In [151]:
x > 3

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True, False]])

In [152]:
x[x > 3]

array([7, 5, 7, 7, 5, 8])

## 8. Homework
### 8.1. Exercise 1:
Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

### 8.2. Exercise 2:
Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

### 8.3. Exercise 3:
Write a NumPy program to reverse an array (first element becomes last).

### 8.4. Exercise 4:
Write a NumPy program to convert an array to a float type.

### 8.5. Exercise 5:
Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

### 8.6. Exercise 6:
Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

### 8.7. Exercise 7:
Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

### 8.8. Exercise 8:
Write a NumPy program to get the indices of the sorted elements of a given array.