# LESSON 3: NUMPY INTRODUCTION - SOLUTION
<img src="../images/np_logo.png" width="400px"/>

## Homework
### Exercise 1:
Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

### Exercise 2:
Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

### Exercise 3:
Write a NumPy program to reverse an array (first element becomes last).

### Exercise 4:
Write a NumPy program to convert an array to a float type.

### Exercise 5:
Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

### Exercise 6:
Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

### Exercise 7:
Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

### Exercise 8:
Write a NumPy program to get the indices of the sorted elements of a given array.

## Solution

In [1]:
import numpy as np

### Excercise 1:

In [5]:
number_list = [1, 2, 3, 4, 5]
number_list

[1, 2, 3, 4, 5]

In [6]:
np.array(number_list)

array([1, 2, 3, 4, 5])

### Excercise 2:

In [7]:
ex_2_array = np.arange(2, 11)
ex_2_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
ex_2_array.reshape((3, 3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Excercise 3:

In [9]:
ex_3_array = np.array([1, 3, 6, 2, 10])
ex_3_array

array([ 1,  3,  6,  2, 10])

In [7]:
ex_3_array[::-1]

array([10,  2,  6,  3,  1])

In [10]:
np.flipud(ex_3_array)

array([10,  2,  6,  3,  1])

### Excercise 4:

In [11]:
ex_4_array = np.array([1, 3, 6, 2, 10])
ex_4_array

array([ 1,  3,  6,  2, 10])

In [12]:
np.asfarray(ex_4_array)

array([ 1.,  3.,  6.,  2., 10.])

### Excercise 5:

In [13]:
ex_5_array = np.ones((5, 6))
ex_5_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
ex_5_array[1:-1,1:-1] = 0
ex_5_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Excercise 6:

In [15]:
ex_6_array = np.ones((8, 8))
ex_6_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# ex_6_array[1::2,::2]
# row: [1::2]: start index = 1, stop index = end, step = 2 => 1, 3, 5, 7
# col: [::2]: start index = 0, stop index = end, step = 2 => 0, 2, 4, 6

In [ ]:
# ex_6_array[::2,1::2]
# row: [::2]: start index = 0, stop index = end, step = 2 => 0, 2, 4, 6
# col: [1::2]: start index = 1, stop index = end, step = 2 => 1, 3, 5, 7

In [14]:
ex_6_array[1::2,::2] = 0
ex_6_array[::2,1::2] = 0
ex_6_array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### Excercise 7:

In [15]:
ex_7_array = np.arange(0, 11)
ex_7_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
ex_7_array = 9 * ex_7_array / 5 + 32
ex_7_array

array([32. , 33.8, 35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. ])

### Excercise 8:

In [17]:
ex_8_array = np.array([1, 3, 6, 2, 10, 5, 8])
ex_8_array

array([ 1,  3,  6,  2, 10,  5,  8])

Step 1: Sort numpy array <br>
1, 3, 6, 2, 10, 5, 8 => 1, 2, 3, 5, 6, 8, 10 <br>
Step 2: Get indices <br>
1, 2, 3, 5, 6, 8, 10 => 0, 3, 1, 5, 2, 6, 4

In [18]:
ex_8_array.argsort()

array([0, 3, 1, 5, 2, 6, 4])