# LESSON 5: TIME SERIES INTRODUCTION
<img src="../images/.png" width="300px"/>

## 1. Overall introduction


## 2. Image processing
### 2.1. Digital image

### 2.2. Task in image processing

## 3. Convolution neural network (CNN)

## 4. Popular CNN architecture
### 4.1. VGG architecture


## 5. Simple implementation
### 5.1. Problem

### 5.2. Solution
``` !conda install -c conda-forge yfinance -y```

In [39]:
from datetime import datetime

import yfinance as yf
import pandas as pd
import numpy as np

#### Prepare data

In [ ]:
tech_list = ['AAPL', 'GOOG', 'MSFT', 'AMZN']

In [ ]:
end = datetime.now()
start = datetime(end.year - 30, end.month, end.day)

In [22]:
df_list = []
for stock in tech_list:
    df = yf.download(stock, start, end)
    df = df.reset_index()
    df['company'] = stock
    df_list.append(df)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [24]:
df = pd.concat(df_list)
df

Date         Open         High          Low        Close  \
0    2002-04-01     0.417500     0.441071     0.415714     0.436786   
1    2002-04-02     0.428571     0.433929     0.426250     0.429821   
2    2002-04-03     0.429464     0.437321     0.421429     0.424107   
3    2002-04-04     0.422679     0.447321     0.422679     0.444643   
4    2002-04-05     0.445536     0.449821     0.430357     0.441786   
...         ...          ...          ...          ...          ...   
5033 2022-03-25  3280.000000  3307.370117  3245.000000  3295.469971   
5034 2022-03-28  3299.500000  3380.750000  3298.000000  3379.810059   
5035 2022-03-29  3407.679932  3416.629883  3357.370117  3386.300049   
5036 2022-03-30  3370.189941  3379.010010  3310.000000  3326.020020   
5037 2022-03-31  3328.895020  3329.899902  3297.919922  3299.330078   

        Adj Close     Volume company  
0        0.374009  199046400    AAPL  
1        0.368045  203795200    AAPL  
2        0.363152  214530400    AAPL  
3        0.380736  338497600    AAPL  
4        0.378290  278348000    AAPL  
...           ...        ...     ...  
5033  3295.469971    2451600    AMZN  
5034  3379.810059    2992700    AMZN  
5035  3386.300049    3307700    AMZN  
5036  3326.020020    2802700    AMZN  
5037  3299.330078     871895    AMZN  

[19550 rows x 8 columns]

In [25]:
df.describe()

Open          High           Low         Close     Adj Close  \
count  19550.000000  19550.000000  19550.000000  19550.000000  19550.000000   
mean     361.093321    364.820410    357.140696    361.078431    359.282129   
std      672.753356    679.836622    665.089306    672.529967    673.385572   
min        0.231964      0.235536      0.227143      0.234286      0.200613   
25%       26.740000     26.980000     26.462499     26.709999     20.397398   
50%       68.968750     69.754997     68.105000     68.985001     67.365421   
75%      302.585258    305.001328    299.164902    302.402504    302.252075   
max     3744.000000   3773.080078   3696.790039   3731.409912   3731.409912   

             Volume  
count  1.955000e+04  
mean   1.257237e+08  
std    2.660388e+08  
min    7.922000e+03  
25%    4.647575e+06  
50%    2.191900e+07  
75%    9.280875e+07  
max    3.372970e+09

#### Visualize data

In [26]:
df

Date         Open         High          Low        Close  \
0    2002-04-01     0.417500     0.441071     0.415714     0.436786   
1    2002-04-02     0.428571     0.433929     0.426250     0.429821   
2    2002-04-03     0.429464     0.437321     0.421429     0.424107   
3    2002-04-04     0.422679     0.447321     0.422679     0.444643   
4    2002-04-05     0.445536     0.449821     0.430357     0.441786   
...         ...          ...          ...          ...          ...   
5033 2022-03-25  3280.000000  3307.370117  3245.000000  3295.469971   
5034 2022-03-28  3299.500000  3380.750000  3298.000000  3379.810059   
5035 2022-03-29  3407.679932  3416.629883  3357.370117  3386.300049   
5036 2022-03-30  3370.189941  3379.010010  3310.000000  3326.020020   
5037 2022-03-31  3328.895020  3329.899902  3297.919922  3299.330078   

        Adj Close     Volume company  
0        0.374009  199046400    AAPL  
1        0.368045  203795200    AAPL  
2        0.363152  214530400    AAPL  
3        0.380736  338497600    AAPL  
4        0.378290  278348000    AAPL  
...           ...        ...     ...  
5033  3295.469971    2451600    AMZN  
5034  3379.810059    2992700    AMZN  
5035  3386.300049    3307700    AMZN  
5036  3326.020020    2802700    AMZN  
5037  3299.330078     871895    AMZN  

[19550 rows x 8 columns]

In [27]:
apple_df = df.loc[df.company == 'AAPL']
apple_df

Date        Open        High         Low       Close   Adj Close  \
0    2002-04-01    0.417500    0.441071    0.415714    0.436786    0.374009   
1    2002-04-02    0.428571    0.433929    0.426250    0.429821    0.368045   
2    2002-04-03    0.429464    0.437321    0.421429    0.424107    0.363152   
3    2002-04-04    0.422679    0.447321    0.422679    0.444643    0.380736   
4    2002-04-05    0.445536    0.449821    0.430357    0.441786    0.378290   
...         ...         ...         ...         ...         ...         ...   
5033 2022-03-25  173.880005  175.279999  172.750000  174.720001  174.720001   
5034 2022-03-28  172.169998  175.729996  172.000000  175.600006  175.600006   
5035 2022-03-29  176.690002  179.009995  176.339996  178.960007  178.960007   
5036 2022-03-30  178.550003  179.610001  176.699997  177.770004  177.770004   
5037 2022-03-31  177.839996  178.029999  175.529007  176.464996  176.464996   

         Volume company  
0     199046400    AAPL  
1     203795200    AAPL  
2     214530400    AAPL  
3     338497600    AAPL  
4     278348000    AAPL  
...         ...     ...  
5033   80470700    AAPL  
5034   90371900    AAPL  
5035  100589400    AAPL  
5036   92540300    AAPL  
5037   28524122    AAPL  

[5038 rows x 8 columns]

In [28]:
close_apple_df = apple_df.Close.values
close_apple_df

array([  0.436786  ,   0.42982101,   0.42410699, ..., 178.96000671,
       177.77000427, 176.46499634])

In [29]:
close_apple_df.shape

(5038,)

#### Prepare config

In [33]:
# Data config
train_val_split_rate = 0.8
train_batch_size = 512
val_batch_size = 512
shuffle_train_set = True
len_features = 50

# Model config
# conv_filters_list = [16, 32, 64, 128, 256]

# Training config
lr = 1e-3
lr_factor = 0.1
lr_patience = 2
lr_min = 1e-10
n_epoch = 100
folder_path = 'audio_example'

#### Split data into train set and val set

In [31]:
train_data = close_apple_df[:int(0.8 * len(close_apple_df))]
train_data

array([ 0.436786  ,  0.42982101,  0.42410699, ..., 41.61999893,
       41.94499969, 41.66999817])

In [32]:
train_data.shape

(4030,)

In [36]:
x_train, y_train = [], []
for i in range(len_features, len(train_data)):
    x_train.append(train_data[i - len_features:i])
    y_train.append(train_data[i])

In [41]:
x_train, y_train = np.array(x_train), np.array(y_train)
x_train.shape, y_train.shape

((3980, 50), (3980,))

In [42]:
x_train

array([[ 0.436786  ,  0.42982101,  0.42410699, ...,  0.39571401,
         0.38214299,  0.383571  ],
       [ 0.42982101,  0.42410699,  0.44464299, ...,  0.38214299,
         0.383571  ,  0.36535701],
       [ 0.42410699,  0.44464299,  0.44178599, ...,  0.383571  ,
         0.36535701,  0.35874999],
       ...,
       [44.04750061, 44.77500153, 44.81499863, ..., 41.23500061,
        43.19250107, 42.08499908],
       [44.77500153, 44.81499863, 44.61500168, ..., 43.19250107,
        42.08499908, 41.61999893],
       [44.81499863, 44.61500168, 44.25      , ..., 42.08499908,
        41.61999893, 41.94499969]])

In [43]:
y_train

array([ 0.36535701,  0.35874999,  0.34892899, ..., 41.61999893,
       41.94499969, 41.66999817])

#### Transform data

#### Build simple LSTM model

In [47]:
def create_lstm_model():
    rnn_model = Sequential([
        LSTM(128, return_sequences=True, input_shape= (x_train.shape[1], 1)),
        LSTM(64, return_sequences=False),
        Dense(dense_units_list[0],),
        Dense(dense_units_list[1])
    ])
    rnn_model.summary()
    return rnn_model

In [49]:
rnn_model = create_lstm_model()

NameError: name 'Sequential' is not defined